### PR TITLE
Updated Build Server

### PR DESCRIPTION
**Pull request by Mechtecs**
Pls enjoy :)

### CODE REVIEW

**Comment by LizzyTrickster** [comment]
No. With the amount of development that goes in with this currently it is not needed, i'm going to remove the build status from the readme

**Comment by Mechtecs** [comment]
WTF Dat speed.

**Comment by LizzyTrickster** [comment]
Email notifications

**Comment by Mechtecs** [comment]
Feel free to add it when its needed.

**Pull request closed without merging**
